[mypy]
namespace_packages = True
disallow_subclassing_any = False

warn_return_any = True
strict_optional = True
warn_no_return = True
warn_unused_configs = True
warn_unused_ignores = True
warn_redundant_casts = True
no_implicit_optional = True
disallow_untyped_defs = True

[mypy-py2app.*]
ignore_missing_imports = True
